unit TestImport1;

interface

// *********************************** 
//   classes for TestImport1.proto
//   generated by ProtoBufGenerator 
//        kami-soft 2016-2017
// ***********************************
uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections,
  pbInput,
  pbOutput,
  pbPublic,
  uAbstractProtoBufClasses,
  Common.AbstractClasses;

type
  TEnumGlobal=(
    gVal1 = 1,
    gVal2 = 2
  );


implementation

end.
